development:
  adapter: postgresql
  database: indeed-development
  username: james
  password: 'password'
  pool: 5

test: &test
  adapter: postgresql
  database: indeed-test
  username: james
  password: 'password'
  pool: 5

production:
  adapter: postgresql
  database: indeed-production
  username: james
  password: 'password'
  pool: 5

cucumber:
  <<: *test
